const Mehandi_categroies=[
    { images:'https://drive.google.com/uc?export=view&id=1CCOC9hi6L3l6gix9Wu73sf0106c3PtkS',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=1zWwF2cqGWxyIw5jIDUKTwmVQeKrkH4of',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=1TzGLW_9NnOZNMBq_EosPGZY-jGwopCUw',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=1IOktbwPbIeONr1uEkNhHx-oAhnt8c5L0',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=12BQzbHYnuL3JsCrB-tfNf8JistMdU8Bl',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=1sFgP4T_HlWN6VO1XcP7PzEHPNOyT3P8m',price: '5000', categroies:"Arabic" },
    { images:'https://drive.google.com/uc?export=view&id=1IbCsQBHNTw75WoGnTvA6iDyqpgD4lDSn',price: '5000', categroies:"Arabic" }, 

    { images:'https://drive.google.com/uc?export=view&id=17y1kThwn6AvsMMPne4qvlIXuMJ2OtiKv',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1gDQv5AuibntjigtZplYCq-4Rzm2Nybyl',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=12d_A3zbquB-FSPEn_cQCFKQFt6YKMEFk',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1QX3HfLCP542k5Ik5BNFHnP9wcU1IgugO',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1PPnEYrdtpB83WbyeJNUuUHh1YaXuhQTf',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1KcMIFikg1YW49FbmW60E6xIHM87k1--H',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=11gg91taNRmPRUlD6eFEDFw8YoND_9ivO',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1MOksRTBfQ2Ju67wnKfylYA6faprsnsAP',price: '5000',categroies:"Indian" },
    { images:'https://drive.google.com/uc?export=view&id=1E1J4UTWeN2NcQ5ryzP6F6AwrFIsI59ta',price: '5000',categroies:"Indian" },

    { images:'https://drive.google.com/uc?export=view&id=17qGlkF2tf8IdL1e4d5ZKpX4kDfvUw64r',price: '500', categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1xEY-2m8kfaqRtJEm-wNX-HjxpWdCtqpv',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1SR3YkPV5w-k_V2faTzB-wEuILZirKUrq',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1PGDb4UmGu4bn6badh24tGVvLHAMwrn0M',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=18MM9_r0aHTG7-sertAG6ekAqis7ZGdeh',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1WiLbvfkvT6DTmFAETff0-LuaZu7RCyGN',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1b_PYdHbZR7ub4yKlFF1B8zwpcCmhtpPT',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1X1K9qayhJxi7HwcazswmDT1l5VwxjZWf',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1s1YZhVgDbO6uXlVtj4chMiUpIE0KBjF3',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1Zh5G4gDZ6Rv3FjHujVifN1JyzB4j_hX7',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1wBH-pp6y2cdlu_j24GmmWR2jZRAPSvu7',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1RqXowhs1ruoRfTfn_YSvzcNI2Fz4KXhU',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=185iEqNqLjGQP-1DEsK6LipHjBcp9z6Aa',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1S1Z8Oh-Q-tMreQI-U763N4ry-DRQCWYt',price: '5000',categroies:"Morocco" },
    { images:'https://drive.google.com/uc?export=view&id=1bE8bGQmC6MAES6DGfb5QdYYK2O1FIgSR',price: '5000',categroies:"Morocco" },

    { images:'https://drive.google.com/uc?export=view&id=1gB82gs4kJ6_0-1FliwATUYZhFDZaGwxa',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1Ucro39YaC9Dtqwqcm_-gSjNmUGbWqe-9',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1cIBB9A5PxzNYVK2QlgF2litBXzNi37H2',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1nMPDoIkIk72pcag_0145OkyheUkCj-Kx',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1HLhKdw79UYBTctr5GGFxiqrIQ9i-07uE',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1VsZxbFvUg4RkQrvVwgg1xu9CuW7_fRsq',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1T6I55OnZLDKSxtKU2BKk4gSwBIF-rWB6',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=11yy3syFuX0Fd-zCP0FvHmCxte_APc0aY',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1wj_CzQFuHn2tyy1Jpk56fmCmE5YI4EZX',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=11TXLut1yRHowLKrfaHmVBdBXh9RXz1OG',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1dG8gNF4vjH9SvDScYXExxHZDgFa7VgHz',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1UQsX76DeRB4GU_LD6HhMbdUiq9qElk29',price: '5000',categroies:"Pakistani" },
    { images:'https://drive.google.com/uc?export=view&id=1kyEa-WViINt9qTcUfkfSiss5gj_QZmh1',price: '5000',categroies:"Pakistani"},
    { images:'https://drive.google.com/uc?export=view&id=17y-jms_Q0X96LGvPLKyY7iBzgDsR9Jve',price: '5000',categroies:"Pakistani"},
    { images:'https://drive.google.com/uc?export=view&id=1LAQKiUEvurIKORiYx1vVsLjS50HhTVuq',price: '5000',categroies:"Pakistani"},

    { images:'https://drive.google.com/uc?export=view&id=1g55ClhHwVlwQlY3EoK7s_WQxASf540zB',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1yipmrGU-y2BVrL7hLn4nCUT7tsTd4Y50',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1SQQYF_UJ_3wpoLYZ9LGX_lAijztEtQvW',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1ypqgumrv6x9oIzP7QxhvTHQWHfLSf6Tl',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1hSNbPJ1-VveAaDYkX1cQmENkcRVuykqh',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1qPHDrjW1xFVB-FQ6OVYaiEgh7Z1IimcI',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1Ub68yO20jYDsl-beRm63piM879NfjD64',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1VVyI1E7OWsfedU3z_h6YYfnPpWZL28-x',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1hNYNlZQdRcuNjUayIxhAwZqdoSPAgsQH',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1YeoVi_AhW49zdlHS-ksJS7vn3BMpUcG2',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1J46G4urQ-GAL7Y_8GWIY1kIvptTkYfaB',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1U0M5BNkBGAV1h6ljJwgwx0nYXb07FeWJ',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1M1lY7riW6I7nJqd4SQu01vMmh0XVCjdY',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=16JQvXj41VmcDvI_upoVNZUwJmT7KGA90',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1xPZZWsPTtNvrgEYhpEBxVWobi5XQ1CSa',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1rWDsFc0OHZ5EWeZD5Jhh997qN8nRAYwS',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1eNrWCT-4NR_HluTd2j4w540IgyrqR5bG',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1o7YqG5I2My_usPSZMLBAwujuTFDqhmwa',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1mQuyATPwG49zu0Tz7UZSqXfp6odAGWcw',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1Zab5OPwxkMq2naAm9VQ8m3wdCTepCgwm',price: '5000',categroies:"Western" },
    { images:'https://drive.google.com/uc?export=view&id=1VyZsP0jeVFxsP23oQzCbz69OrKYJUQ-e',price: '5000',categroies:"Western" },
    
]
export {Mehandi_categroies};