const Top_categories=[
    { category:"Anarkali",images:require('./Images/anarkali.jpg'),name:'Anarkali'},
    { category:"PattuSaree",images:require('./Images/Pattu Saree.jpg'),name:'Pattu Saree'},
    { category:"Saree",images:require('./Images/Sarees.jpg'),name:'Sarees'},
    { category:"Anarkali_Serwani",images:require('./Images/anarkali serwani.jpg'),name:'Anarkali Serwani'},
    { category:"Dhorti_Serwani",images:require('./Images/Dhoti serwani.jpg'),name:'Dhoti Serwani'},
    { category:"Jodhpuri_Suits",images:require('./Images/Jodhpuri Suits.jpg'),name:'Jodhpuri Suit'},
    { category:"Kurta",images:require('./Images/Kurta.jpg'),name:'Kurta'},
    { category:"Serwani",images:require('./Images/Sherwani.jpg'),name:'Sherwani'},

]
const Bride_collections=[
    {     image:'https://drive.google.com/uc?export=view&id=1L-v7s6YLj_4e3qKhZHP_SX6jugbsCdGr',   name:'1 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1j1iuAkEbPoa53v3qhZudXv3udlcwOyAp',   name:'2 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1d-ftuCqbN29eKdeOdti0aCON850e5m0I',   name:'3 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1oB7K0Ik9ZkbVaWCwPgV0hRpypRAaj3w_',   name:'4 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=19NGFTtvIBRx5vtUCDkoYwRIqU6xT1oRv',name:'',price:'' },
    {     image:'https://drive.google.com/uc?export=view&id=1xerR9lmNaAfkz42fEPGXt9S8gx-q-VaX',   name:'6 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1L-v7s6YLj_4e3qKhZHP_SX6jugbsCdGr',name:'',price:'' },
    {     image:'https://drive.google.com/uc?export=view&id=1O4EqlHfNn-vIN0_YRqvLbMg7sVQ2LdJH',   name:'7 Name ',  price:'500 '},
    {     image:'https://drive.google.com/uc?export=view&id=1oZCGR97QO2bkt_5oaU7JV1vya6rgg-Z5',   name:'9 Name ',  price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1bEk7KyNFMnEJ0K0joNFbk-RiWs3rA1--',   name:'10 Name ', price:'5000 '},
]
const  Shoe_collections=[
    {     image:'',   name:'1 Name ', price:'5000 '},
    {     image:'',   name:'2 Name ', price:'5000 '},
    {     image:'',   name:'3 Name ',  price:'5000 '},
    {     image:'',   name:'4 Name ',  price:'5000 '},
    {     image:'',   name:'5 Name ',  price:'5000 '},
    {     image:'',   name:'6 Name ',  price:'5000 ' },
    {     image:'',   name:'7 Name ',  price:'5000 '},
    {     image:'',   name:'8 Name ',  price:'5000 '},
    {     image:'',   name:'9 Name ',  price:'5000 '},
    {     image:'',   name:'10 Name ',  price:'5000 '},
]
const Groom_collections=[
    {     image:'https://drive.google.com/uc?export=view&id=1PUGcwGh5IBW66UNrziElXx-cqJ2Zq5qv',   name:'Name ',    price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1HvwRNIbXxpj5O6R7a8SPL1YFJGY3DNcd',   name:'Name ',    price:'50 '},
    {     image:'https://drive.google.com/uc?export=view&id=1GBv2M29MeU98PfJ77PxnOBDflOflfQuG',   name:'3 name',   price:'5000'},      
    {     image:'https://drive.google.com/uc?export=view&id=1R4vL36VCZSVDJHlASvU1Jnxd7i4ByeGF',   name:'4 Name',   price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1_x4X1Th92N1g-yUOvbe3Kb7KSt0dWI1Q',   name:'5 name',   price:'5000'},    
    {     image:'https://drive.google.com/uc?export=view&id=1WG_kGvLfCfeVvTD7mT6KJalSD-WxTBmC',   name:'6 Name',   price:'5000 ' },
    {     image:'https://drive.google.com/uc?export=view&id=13P03m7_vnIC5cjla6dwc3XC11zIEhjno',   name:'7 name',   price:'5000'},    
    {     image:'https://drive.google.com/uc?export=view&id=1UnpTZJ3s95ocqsc95mc0ltQMmz7YKAYb',   name:'8 Name',   price:'5000 '},
    {     image:'https://drive.google.com/uc?export=view&id=1tdaT_aEVOGAhCI8PprbBcU-shQ_8rRGm',   name:'9 name',   price:'5000'},   
    {     image:'https://drive.google.com/uc?export=view&id=1CVkfR6M3mLcl3zXReqyTmfgPV88nNd_p',   name:'10 Name',  price:'5000 '},
     
]
const Boutique_Products=[

                //     anarkali 
    {  images:'https://drive.google.com/uc?export=view&id=1IDUTrqjgFMPayo1gTJqrfjOkza3sHwm_',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1GH4FWA2f5pSbORwP6gF58lsub8kXngld',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1j1iuAkEbPoa53v3qhZudXv3udlcwOyAp',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=16ieuTZ6SlPPtr32OV8C_pJ-C0UITYQWM',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1JAflBpXsxp_XNlTq_3Rvdh2uFPMOIx28',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=16uIt4t5SkFc0KYwcZVpZTfYEbS_MxCC2',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1d-ftuCqbN29eKdeOdti0aCON850e5m0I',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1q3X_kg6HnCi_6i3SijrwZMQvYpTnyRsq',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1lxR6gY4XXeFN3dHpaVtN2iEoM088XnS9',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1ViPrzOJqSKBuWtPIFTIEXcDeenazXq4o',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1WqU-OXTvud28Yztk9afKKn9sBUQl2BFx',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1L-v7s6YLj_4e3qKhZHP_SX6jugbsCdGr',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1DQWYBN_XBNJ1iitM9wEfN0Yi34_nJ9sy',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1F8wVioqMUhh6hph4_P7zi4bEElN1diJc',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=12GW5tAxztLv44kJxP3wCAe3arziBxjIX',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=12tbL7VmAkPmYb5huLLokfIqKDNC4dN8r',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1l0Bpwvbw5NLyj85pzon3eFiQ4svoxEyN',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=19NGFTtvIBRx5vtUCDkoYwRIqU6xT1oRv',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1tNQmTIycHzfnEHrPSGgYory6M9WB6W2O',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1v678EN46LDNQ22FXi85HYnsx-rhFpNSe',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1BCdC5neT0f6stFsS-achKNpABFiLudY6',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1JfVOsAfUgAJVUKMqlToYdbvhlhBH2xf4',name:'',price:'',categroies:"Anarkali" },
    {  images:'https://drive.google.com/uc?export=view&id=1mDmv3eVW5WIsX8GhNX67CS5WsINSMdiQ',name:'',price:'',categroies:"Anarkali" },
                    //  pattu sarees
    {  images:'https://drive.google.com/uc?export=view&id=1ri6EvHtxAOdiR7PsPAfKi9uQWkf2pGor',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1Rc9XnUaEMnZTUgY6-CtsCBOnBL0utMxI',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1werKmW1YohieitzOvQ-YlPzHa8KFssTw',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1I9fjp-BTfhQg3bpgo9C18S6Up3E5QmuG',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1oB7K0Ik9ZkbVaWCwPgV0hRpypRAaj3w_',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1cF5xGJ46W02XGpNIgEij5FRGViCnHBtU',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1oZCGR97QO2bkt_5oaU7JV1vya6rgg-Z5',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1JeRmS51eLZE0Rhvi8WwCuwypoaGb4vja',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1cjHBtCSVlzYmuTeYC1B5SNlDQlVYgApb',name:'',price:'',categroies:"PattuSaree" },
    {  images:'https://drive.google.com/uc?export=view&id=1JswhJNPhu2z5SRne6jGsxE6TJZt6vIL-',name:'',price:'',categroies:"PattuSaree" },
    // sarees
    {  images:'https://drive.google.com/uc?export=view&id=1N0qLS1F9wFOsmUuZecKeMQwvBsy0gOoc',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1Eol41I4Fy85EvaJpyPJLoRnivSEdOvDB',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1bEk7KyNFMnEJ0K0joNFbk-RiWs3rA1--',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=15kaVVrpiyFGVlk1pBNxN_cBNunxI8FtG',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1K2bdC02dzgFdNop8GsIiGVesq2vLUZI4',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1fZLyEzZYzPEYKroD6a0douW-kAxM4p3N',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1jxAy7duSzMngngCLLCa0MK4qFtNMSBjK',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1luU55gwtPJNJkHhpn_FUcaY488CcZqS7',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1xerR9lmNaAfkz42fEPGXt9S8gx-q-VaX',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1GmOy8esA-fT0_Zj2XHrWLKLlgfE6eZN8',name:'',price:'',categroies:"Saree"},
    {  images:'https://drive.google.com/uc?export=view&id=1kKbIOU1H9mkeNA5WCnrIxjFW3HNmG5sp',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1bwngngTP4IZYi-3M695bAelTbo4EROiC',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1tUpBQCgLHAKY4zI3NnIyVj-jbD-qj7RW',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1h9L_DqnuYf3LQVmcSbNLtiRxEJvWTEJl',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1un-_1bREDxHRQ1w_91Ik5MLlhYMDPoYF',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1SYkmIU3l2qP-HGZRG8atZSt4L1pRwGmo',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1U4Mz3uTQF1CEOWjB9nrapKX6Cl5XXwxl',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1ozsHdYEgWwzi_y7dPJMFz0-ZDdeFXQB4',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1q6k_7-9VDC1EDt-OWg-gKt-9ytUoysuS',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1O4EqlHfNn-vIN0_YRqvLbMg7sVQ2LdJH',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=1PJKW42doF8a11oT8teZepJPON_2IeUd6',name:'',price:'',categroies:"Saree" },
    {  images:'https://drive.google.com/uc?export=view&id=16t5sKyi4xlcZJWVQAOFvvQxtrr3Y8M15',name:'',price:'',categroies:"Saree" },
            // anarkali serwani
    {  images:'https://drive.google.com/uc?export=view&id=1oa9c6Xd3deLwmWQqaN_GhqFMOrsyfBTE',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1Y5Hbi5G59sban47QVCrbNo5S1M08Ct96',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1pLo6YtKy8OCHw91BO1SY1DunIhKKbx23',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1vyf7tCQfXJiGW1_M3iRO_6cRiqcQG6Zd',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1R4vL36VCZSVDJHlASvU1Jnxd7i4ByeGF',name:'',price:'',categroies:"Anarkali_Serwani" }, 
    {  images:'https://drive.google.com/uc?export=view&id=1Z_iKcP6JwX4dIfvwgm589rweRnG_VdMJ',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=18JO2GNNMx_yWUjQlzuw6vp2c-LgFS2Lx',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1_WLdEVY_r4aw6UCZqlHE9cxqvtCVyyTv',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1EhDlRZR7EyhkhBEene6d9BfT3L7CRUic',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1tUpGA_ADF8CEPtZ983kcCU4mgAySNq2L',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1HvwRNIbXxpj5O6R7a8SPL1YFJGY3DNcd',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=10Wn3vgYMrkjXYHXFj6WI1ziomd4Viec7',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1vW3sESS_MATJEY-BNn63qmFP2WUJqXCW',name:'',price:'',categroies:"Anarkali_Serwani" },
    {  images:'https://drive.google.com/uc?export=view&id=1UnpTZJ3s95ocqsc95mc0ltQMmz7YKAYb',name:'',price:'',categroies:"Anarkali_Serwani" },
    // Dhoti serwani
    {  images:'https://drive.google.com/uc?export=view&id=1G7aixB4K_IP4iRitraefiiZYx38n9InO',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1zzmx6d-AMu9UeyaNnMBt5-mA6n-Mdrws',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1CVkfR6M3mLcl3zXReqyTmfgPV88nNd_p',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1x4CPSr9LzDKaJuhr_ThnVnM24f9radIa',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1qdSOrkE2DXodkn2UQgXZqbtIOoSnin33',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1TPx0RXNA2CXdV_C_qtbjvls7g2O3bXdR',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1_x4X1Th92N1g-yUOvbe3Kb7KSt0dWI1Q',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1WG_kGvLfCfeVvTD7mT6KJalSD-WxTBmC',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1-b2Th2MrS7YCPFWSi_ltgh8Q57xTKixs',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1_SfhmS5r8wBprqBMV-snWvfptOneiblW',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1xvqfzHULLVbEeRxwC8FrIyraWFMO072w',name:'',price:'',categroies:"Dhorti_Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1u7Pj3fH_EL6LfN82ayDy_B9XH7I_tsOw',name:'',price:'',categroies:"Dhorti_Serwani"},    
// jodhpuri suits
    {  images:'https://drive.google.com/uc?export=view&id=1RAd38CbDKgbuh43adXo2GnmNL2d8mUtD',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    {  images:'https://drive.google.com/uc?export=view&id=18EXgw4d-C1V1uhNJO9s8LZg1V_VqEeDz',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    {  images:'https://drive.google.com/uc?export=view&id=1PUGcwGh5IBW66UNrziElXx-cqJ2Zq5qv',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    {  images:'https://drive.google.com/uc?export=view&id=1Lfmq1EyydXY3wgUbW2LFiVwUnVzZ2lPS',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    {  images:'https://drive.google.com/uc?export=view&id=1tbFKO_cqXiLCNO-NmWcFOmb2Mzbz2EVK',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    {  images:'https://drive.google.com/uc?export=view&id=1K5jDo_WhQB-p3pa9fdNgDXbJLvpdgmIp',name:'',price:'',categroies:"Jodhpuri_Suits"},    
    // kurta
    {  images:'https://drive.google.com/uc?export=view&id=1MuQ3u_A27Ey4q-HRIufJrbj__0pe_zR-',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=19OmKPz_nnkVLLfVZp73LoOFIn4YemunH',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1W6RygyttXtssjOY9Unvuq4rS1hp6L40S',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1rI1Mjc77_w73QlN8qmuL1DU1ZO-zj4JS',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1KSKeaAC0_0B0u1IowQ7F6p6M-r7qhK1o',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1pyDoBARoeqKIm4FppVcthqqcw-afMbI-',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1cLGbxppOrvUsKtkJJ0dBZya62qcYj70r',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1iB8WCVYtWh1xAdYjx_BMyhUuIcnUViKu',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1_nEO_m0M1M590HrU7vHqAwvGar4VS9jm',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=13P03m7_vnIC5cjla6dwc3XC11zIEhjno',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1tdaT_aEVOGAhCI8PprbBcU-shQ_8rRGm',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1Eyi-1Biqyydov9aR3KfCpl9MzbOwDk7g',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1_ASUKy2R5dICJqH_S-8bf3yKgcghylwt',name:'',price:'',categroies:"Kurta"},    
    {  images:'https://drive.google.com/uc?export=view&id=1mhERbJMYqpqZiukCftPqjprPXJMgW93v',name:'',price:'',categroies:"Kurta"},  
// serwani
    {  images:'https://drive.google.com/uc?export=view&id=1qHGSvyytQzqv_lNOUdB0Z7FuMseR7MFe',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1pZ8cjMmgWJPnl7Fawyx8EGxumdVKvjeb',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=16oW3kYOfrjmsY8fInKfDKttbe4uUeFVT',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1I3l4lcGGdETVnWLGczAHXHIGEAsUXkP4',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1uSdr3dNOpECWK_nUZkh8bKipw0fUwPfU',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=14eNHLe5WguKftrNX6JF7TEgDYt1JgPWJ',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1MlKVgM8MDbTiofJroyGMTOb7bSfUoFXD',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1kb-G41bFA5FCBJTBBZw0CBLXG1H9RmTj',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1Gj0I2STbq12GW82-mt7MMME7Mk25h202',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1yuWIvIw1EDExHA9_UbQH6jDMNRY7jIIf',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1fTNd1T2c308xsW_RkIbrIBN-3rsUO-jP',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1DmYf8Y2JtZPfTGt5kroYDbOkS3WtcH0a',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1ZBBOXDVf5a0j1srN8pLz8PTRuluekGoo',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1U_OqitbWrsUkxKYk4jm21DAjDKdex-h3',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1qtD2iiH5tnnrOLxVMoGAAy2PNxGsTKO4',name:'',price:'',categroies:"Serwani"},    
    {  images:'https://drive.google.com/uc?export=view&id=1GBv2M29MeU98PfJ77PxnOBDflOflfQuG',name:'',price:'',categroies:"Serwani"},      
]

export {Bride_collections,Shoe_collections,Groom_collections,Top_categories,Boutique_Products};
